language: python
python:
  - "2.7"
#Start postgres
services:
  - postgresql
# command to install dependencies
install: "pip install -r code/requirements.txt"
#create database
before_script:
  - psql -c 'create database master_4156_database;' -U postgres
  - pip install coverage
  - chmod ugo+x ./start-simulator.sh
  - ./start-simulator.sh
# command to run tests
script:
  - cd code && coverage run --source=app/  -m unittest discover tests
  - coverage report -m