language: python
python:
  - "2.7"
#Start postgres
services:
  - postgresql
# command to install dependencies
install: "pip install -r code/requirements.txt"
#create database
before_script:
  - psql -c 'create database master_4156_database;' -U postgres
  - python simulator.py
# command to run tests
script:
  - cd code && python -m unittest discover tests