language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r code/requirements.txt"
# command to run tests
script:
- python exchange_simulator/server.py &
- python simulator.py &
- python -m unittest discover code/tests